src/Entity/Category.php
<?php
namespace App\Entity;

use App\Entity\Trait\LastUpdateTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Serializer\Annotation\Groups;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: \App\Repository\CategoryRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[Vich\Uploadable]
class Category
{
    #[ORM\Id, ORM\GeneratedValue, ORM\Column]
    #[Groups('Category')]
    private ?int $id;

    #[ORM\Column(length: 100)]
    #[Groups('Category')]
    private string $title;

    #[ORM\Column(length: 255, nullable: true, options: ['default' => null])]
    #[Groups('CategoryDetails')]
    private ?string $image = null;

    #[Vich\UploadableField(mapping: 'category_images', fileNameProperty: 'image')]
    #[Groups('CategoryDetails')]
    public ?File $file = null;

    #[ORM\ManyToMany(targetEntity: Dossier::class, inversedBy: 'categories')]
    /** @var Collection<int, Dossier> */
    private Collection $dossier;

    use LastUpdateTrait;

    public function __construct()
    {
        $this->dossier = new ArrayCollection;
    }

    public function __toString(): string
    {
        return $this->getTitle();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function getImageRelativePath(): ?string
    {
        return ($this->image) ? '/images/category/'.$this->image : null;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function setImageFile(?File $image = null): self
    {
        $this->file = $image;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->file;
    }

    /**
     * @return Collection<int, Dossier>
     */
    public function getDossier(): Collection
    {
        return $this->dossier;
    }

    public function addDossier(Dossier $dossier): self
    {
        if (!$this->dossier->contains($dossier)) {
            $this->dossier[] = $dossier;
        }

        return $this;
    }

    public function removeDossier(Dossier $dossier): self
    {
        if ($this->dossier->contains($dossier)) {
            $this->dossier->removeElement($dossier);
        }

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% if title is not empty %}{{ title }} - {% endif %}Symfony App{% endblock %}</title>
        {% block stylesheets %}
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        {% endblock %}
    </head>
    <body class="{{ class_body|default('d-flex flex-column h-100') }}">

        {% block menucontainer %}
        <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item"><a class="nav-link active" href="{{ path('dossierList') }}">Index</a></li>
                    <li class="nav-item"><a class="nav-link" href="http://localhost:1080" target="_blank">Mailer</a></li>
                    <li class="nav-item"><a class="nav-link" href="http://localhost:8080/?route=/database/structure&db=poc-messenger" target="_blank">PhpMyAdmin</a></li>
                    <li class="nav-item"><a class="nav-link" href="http://localhost:15672" target="_blank" title="Login/Password: guest/guest">RabbitMQ Front</a></li>
                    <li class="nav-item"><a class="nav-link" href="//symfony.com/doc/current/">Symfony Doc</a></li>
                    {% block menu %}{% endblock %}
                    {% if not app.user %}
                        <li class="nav-item"><a class="nav-link" href="{{ path('app_login') }}">Login</a></li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{{ path('app_logout') }}">Logout</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        {% endblock %}

        {% block bodycontainer %}
        <main class="{{ class_main|default('container') }}" role="main">

            {% if title is not empty %}<h1>{{ title }}</h1>{% endif %}

            {% for label, messages in app.flashes %}
                {% for message in messages %}
                    <div class="alert alert-{{ label }}" role="alert">{{ message }}</div>
                {% endfor %}
            {% endfor %}

            {% block body %}{% endblock %}
        </main>
        {% endblock %}

        {% block javascripts %}
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
        {% endblock %}
    </body>
</html>

templates/dossierItem.html.twig
{% extends "base.html.twig" %}
{% set title = 'Dossier #' ~ dossier.id %}

{% block body %}
    <p>
        Title: {{ dossier.title }}, client: {{ dossier.client.name }}.<br>
        Date: {{ dossier.createdDate|date('d/m/Y') }} by {{ dossier.author.name }}<br>
        Status: {{ dossier.status.name[:1]|upper ~ dossier.status.name[1:]|lower }}<br>
    </p>
    <p>{{ dossier.content }}</p>

    {% if dossier.categories is not empty %}
    Categories:
    <div class="container">
        <div class="row">
            {% for category in dossier.categories %}
            <div class="col-3" style="text-align: center; padding: 10px;">
                {% if category.imageRelativePath is not empty %}
                    <img src="{{ asset(category.imageRelativePath) }}" alt="category logo"><br>
                {% endif %}
                <span>{{ category.title }}</span>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}

    {% if dossier.comments is not empty %}
        <br>
        <h3>Comments:</h3>
        <div class="container">
            <div class="row">
                {% for comment in dossier.comments %}
                    <div class="col-12" style="padding: 10px;">
                        <p>
                            <strong>On {{ comment.createdDate|date('d/m/Y') }}, by
                                {% if comment.author is not empty %}
                                    {{ comment.author.username|capitalize }}
                                {% else %}
                                    <em>Deleted user</em>
                                {% endif %}
                            </strong><br>
                            <span>{{ comment.content|nl2br }}</span>
                        </p>
                        <hr>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}

    {% if app.user %}
        {{ form(formComment) }}
    {% else %}
        <p>You can <a href="{{ path('app_login') }}">log in</a> for post comment.</p>
    {% endif %}
{% endblock %}

templates/dossierList.html.twig
{% extends "base.html.twig" %}
{% set title = 'Dossier '~ status.name|lower ~' List' %}

{% block body %}
    {% for dossier in dossierList %}
        <div>
            <p>
                Title: {{ dossier.title }}, client: {{ dossier.client.name }}.<br>
                Date: {{ dossier.createdDate|date('d/m/Y') }}<br>
                <a href="{{ path('dossierItem', {'id': dossier.id}) }}">Consult dossier</a>
                <em style="font-size: 0.9em">
                    {% if dossier.comments.count > 0 %}
                        ({{ dossier.comments.count }} comments)
                    {% else %}
                        (no comments)
                    {% endif %}
                </em>
            </p>
        </div>
    {% else %}
        <p>No dossiers.</p>
    {% endfor %}

    <div class="navigation">
        {{ knp_pagination_render(dossierList) }}
    </div>

    <p>Consult dossiers in status:
        {% for item in status.cases %}
            {% if (item.value != status.value) %}
                <a href="{{ app.request.pathInfo }}?status={{ item.value }}">{{ item.name|lower }}</a>
                {% if (loop.last == false) %}-{% endif %}
            {% endif %}
        {% endfor %}
    </p>
{% endblock %}